### PR TITLE
Update procmem_yara.py 

### PR DESCRIPTION
**Pull request by cccs-mog**

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks, the problem of expose strings, is that it helps in leaks of private yara, we need to add some configuration for that first

**Comment by cccs-mog** [comment]
Yeah that make sense. Let me know if I can help in any way.

**Comment by doomedraven** [comment]
Yes, I just need to think about how to properly handle that, not sure if just add conf option and read it in sig and put under if, what do you think? + Which config should we use

**Comment by cccs-mog** [comment]
I think it would be ideal to have a optional private field/conf option in the sig themselves which are to be private and the procmem_yara rule look for this field and don't expose if it's private instead of having the rule procmem_yara be an on/off feature. I will make the change. Thanks for the feedback !

**Comment by doomedraven** [comment]
Is about string field, not sig on/off

**Comment by cccs-mog** [comment]
Yes correct, what I meant was either no strings or strings should not be enabled/disabled for everything but a rule specific behavior which is controlled(checked) via the procmem_yara.

**Comment by doomedraven** [comment]
@kevoreilly

**Review by cccs-kevin — APPROVED** [review]

**Comment by cccs-kevin** [comment]
> @kevoreilly

👀

**Pull request merged**
