### PR TITLE
Update Yara CI config

### PR DESCRIPTION
**Pull request by adepasquale**
1. Disable FP and FN checks as agreed with @kevoreilly 
2. Update or remove Yara strings that slow down scanning
3. Add constraints to unlimited greedy regex in Yara

I can revert 2 and 3 if you'd rather keep some of these low-perf rules.

### CODE REVIEW

**Comment by r0ny123** [comment]
why do you disable FP and FN check?

**Comment by adepasquale** [comment]
There are literally thousands of matches, see https://github.com/adepasquale/CAPE-community/runs/24777647826 (capped to 1000). We agreed with @kevoreilly it would have been quicker to just skip them.

**Comment by adepasquale** [comment]
That said, if you'd rather keep those checks I can attempt to build a bigger ignore list.

**Comment by kevoreilly** [comment]
Yeah the sheer number of FPs was ridiculous - but more than that, the prospect of changing the detections to remove the FPs whilst maintaining the same TP rate seems almost intractable. I think disabling is the most practical solution.

**Pull request merged**
