### PR TITLE
Create Amadey.yar

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by ditekshen** [comment]
This may cause conflict with https://github.com/kevoreilly/CAPEv2/blob/master/data/yara/CAPE/Amadey.yar. That's why an ```Amadey``` rule does not exist in community repo in the first place.

**Comment by r0ny123** [comment]
Thanks for pointing out. That rule is too old. I think I should create a separate PR on the main repo or deprecate that rule from the main repo. @kevoreilly thoughts?

**Comment by kevoreilly** [comment]
Thank you for bringing to my attention the fact that the signature in the main repo is out-of-date. However, when looking at the proposed replacement, I noted that it falls foul of several of the guidelines I like to follow for cape's yara; it detects based on strings rather than code, it detects based on a single pattern and finally it detects based on a pdb string. It is of course trivial for the attackers to remove the pdb string from future samples.

I therefore looked at my own signature from a few years ago and saw that of the two patterns it requires, one is still hit by current samples. Therefore, by adding two characteristic code patterns from recent samples, I have revived this signature. Please do let me know if you see any samples that are not detected by this update: https://github.com/kevoreilly/CAPEv2/commit/27065f73f6c3735061f940dc223e6aa584f7d395

Since new yara is enforced now in cape, I took note of the `pe.is_pe` condition from this PR replacing the hideous `uint16(0) == 0x5A4D` and introduced it into my update. I will do this for all signatures going forward. Thank you.

**Comment by r0ny123** [comment]
Thank you for the update. I appreciate it. While I am a fan of code-based signatures, I confess I was too lazy to write one this time. However, I will inform you if I discover any new variations. I promise that next time, I will use a code-based signature. (You are aware of my previous contributions ;))

**Pull request closed without merging**
